### ISSUE TITLE
incompatibility with werewolves addod

### ISSUE THREAD

**Issue by SilveroGhost** [SSKirillSS/relics#122]
Relics version: 1.20.1 - 0.6.2.1
Werewolves- become a beast! version: 1.20.1- 2.0.0.0

Hello, while making a custom modpack I discovered an incompatibility between relics and the vampirisim mod addon: Werewolves- Become a beast! I am not sure how, if possible, to fix it on my end 

link to the crash report: https://pastebin.com/jvpQn2cu

**Comment by Vebste1** [comment]
Greetings. I'd like to have more info on your loader, its version and your modpack (aka info about the installed mods) because when I tried to install newest version of relics, all of its required mods and vampirism with werewolves I couldn't recreate the issue.
![2024-03-15_22 27 16](https://github.com/SSKirillSS/relics/assets/130890552/ea5966c9-7cbb-4b22-971a-0a0de7429913)
