### ISSUE TITLE
[1.20.1] Entity ticking crash when equipping Ice Skates and Roller Skates

### ISSUE THREAD

**Issue by NeuTraLZero** [SSKirillSS/relics#158]
Relics version 0.8.0.2
Forge 47.3.5

I have tried with every other relics and only these 2 caused a crash

[logs](https://github.com/user-attachments/files/16462562/2024-08-02-3.log.gz)

https://github.com/user-attachments/assets/e2b9798a-898e-48a9-bf30-2ada0fa9401d

**Comment by SSKirillSS** [comment]
Basically, to fix this issue, you may just switch from Forge to NeoForge (which is recommended since all Relics' tests were made on NeoForge only). But if you want to keep Forge, you can join our [Discord](https://discord.gg/pHren9yxzW) (and tag me in any channel), and I'll provide you a build with potentially fixed compatibility to be sure that it works fine on Forge too now.

**Comment by SSKirillSS** [comment]
Should be fixed now.
