### ISSUE TITLE
Ticking Entity crashing the server

### ISSUE THREAD

**Issue by qochwip** [SSKirillSS/relics#182]
Modpack: ATM 10 1.15

Stalactite proced and hit another player, causing a server crash. 

Fixed by deleting the mod and rarcompat and lauching the server again. The launch sequence skipped the stalactite entities and no crash occured. 

Crash log: https://pastebin.com/xh564Kbs

**Comment by SiverDX** [comment]
seems to be caused by https://www.curseforge.com/minecraft/mc-mods/corail-tombstone

This code snippet to be exact
```java
public static ServerPlayer getPlayerForLogin(MinecraftServer server, GameProfile profil) {
    return server.getPlayerList().getPlayerForLogin(profil, (ClientInformation)null);
}
```

vanilla calls `this.updateOptions(clientInformation)` in the `ServerPlayer` constructor
and in there this call occurs `this.language = clientInformation.language()`

which causes the exception you see in that crash log

**Comment by Corail31** [comment]
@SSKirillSS @SiverDX I added a default ClientInformation to that method to 1.21.1 version for the next release (it was time to change it), but this method is only used when a 'Receptacle of Familiar" tries to capture a tamable entity having a player owner not being present on the server.
So, it doesn't correspond to the @qochwip explanation about "stalactite" entities hitting a player (maybe the wolf in the log).
