### ISSUE TITLE
some artifacts cancel other sources of the same effect

### ISSUE THREAD

**Issue by Jackiecrazy** [SSKirillSS/relics#20]
I've noted this with the midnight robe, camouflage ring, and blazing flask. Midnight robe and camouflage ring will cancel invisibility potions and the scarf of invisibility from artifacts (the mod), and blazing flask will cancel any form of flight, including creative and spectator mode (you'll fall straight into the void upon switching to spectator). Doesn't look like anything else does this for now.

**Comment by SSKirillSS** [comment]
Should be fixed in:
\> Blazing Flask: https://github.com/SSKirillSS/relics/commit/e97732f16408713519b6f01e5a7f220d9874fd45
\> Midnight Robe: https://github.com/SSKirillSS/relics/commit/c746d1db04ff586f01088cd78ad5b0cb0b117c2f
\> Camouflage Ring: https://github.com/SSKirillSS/relics/commit/759c6beac5a4671a818aad1a72f325f0d3b04342

Will be implemented in the next mod update.
